name: Next.js 14 Project CI
run-name: ${{ github.actor }} is testing Next.js 14 project 🚀
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint check and capture any errors
      - name: Run linter
        run: npm run lint
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build the project and check for build errors
      - name: Build the project
        run: npm run build
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run tests and check for test errors
      - name: Run tests
        run: npm test
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionally, list files in the repository
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      # Check for job status and print error messages if the previous steps failed
      - name: Check for errors
        if: failure() 
        run: |
          echo "❌ An error occurred in one of the previous steps."
          echo "🚨 Linter or build errors occurred during the process. Please check the logs for details."

      - run: echo "🍏 This job's status is ${{ job.status }}."
