name: Next.js 14 Project CI
run-name: ${{ github.actor }} is testing Next.js 14 project 🚀
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build command
      - name: Build the project
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm test

      # Check for linting issues
      - name: Run linter
        run: npm run lint

      # Optionally, list files in the repository
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
